{'type': 'message', 'likeCount': 0, 'replyCount': 0, 'viewCount': 1, 'tags': [],
 'highlightSubject': '<em class="jive-hilite">Discussion</em> and <em class="jive-hilite">reply</em> with <em class="jive-hilite">attachment</em> by <em class="jive-hilite">Email2017</em>-<em class="jive-hilite">05</em>-<em class="jive-hilite">03T12</em>:<em class="jive-hilite">07</em>:<em class="jive-hilite">44.582516</em>',
 'followed': False, 'content': {'type': 'text/html',
                                'text': '<body><!-- [DocumentBodyStart:33012154-d239-4a9e-b51a-d0f2d3ebfeb5] --><div class="jive-rendered-content"><div><div data-so-md5="028f0e7e96b77f5a10596deef485e729"> </div><div class="j-rte-table"><table style="margin-top: 0px; margin-bottom: 0px;" width="100%"><tbody><tr style="border-top: solid 1px #a9a9a9; padding-top: 7px;"><td style="color: #555555;font-family: arial;font-size: 12px;width: 30px;font-weight: bold;">From:</td><td style="font-family: arial;font-size: 12px;"><span>CNC1 Tester1 &lt;</span><a class="jive-link-email-small" href="mailto:cnctester1@dev.thoughtworks.com">cnctester1@dev.thoughtworks.com</a><span>&gt;</span></td></tr><tr style="border-bottom: solid 1px #a9a9a9; padding-bottom: 7px;"><td style="color: #555555;font-family: arial;font-size: 12px;width: 30px;font-weight: bold;">To:</td><td style="font-family: arial;font-size: 12px; padding-bottom: 10px;"><span>taohui-automation&lt;</span><a class="jive-link-email-small" href="mailto:streamonce-automation@dev.thoughtworks.com">streamonce-automation@dev.thoughtworks.com</a><span>&gt;; taohui-automation&lt;</span><a class="jive-link-email-small" href="mailto:streamonce-automation@dev.thoughtworks.com">streamonce-automation@dev.thoughtworks.com</a><span>&gt;;</span></td></tr><tr><td colspan="2" style="padding-top: 10px;&gt;&lt;div class=;"><br/> &#160; &#160; &#160; &#160; &#160;After a growth interval, the polyp begins reproducing asexually by budding and, in the Scyphozoa, is called a segmenting polyp,<br/> &#160; &#160; &#160; &#160;or a scyphistoma. Budding produces more scyphistomae and also ephyrae. Budding sites vary by species; from the tentacle bulbs,<br/> &#160; &#160; &#160; &#160;the manubrium (above the mouth), or the gonads of hydromedusae.[51] Polyps asexually produce free-swimming ephyra,<br/> &#160; &#160; &#160; &#160;which then become a medusa. New specimens (usually only a millimeter or two across) swim away from the polyp and then grow.<br/> &#160; &#160; &#160; &#160;Some polyps can asexually produce a creeping frustule larval form, which then develops into another polyp.<br/> &#160; &#160; &#160; &#160;</td></tr></tbody></table></div><hr style="height:1px;border:none;background-color:#a9a9a9;color:#a9a9a9;"/><div class="j-rte-table"><table cellpadding="7px" width="100%"><tbody><tr><td style="vertical-align:top; padding-top:5px;" valign="top" width="79%"><span style="font-size: 11px;color:#a9a9a9;">Comments/replies will be emailed to:<br/><a class="jive-link-email-small" href="mailto:cnctester1@dev.thoughtworks.com">cnctester1@dev.thoughtworks.com</a><span>; </span><a class="jive-link-email-small" href="mailto:streamonce-automation@dev.thoughtworks.com">streamonce-automation@dev.thoughtworks.com</a><span>;</span></span></td><td style="border-left:1px solid #c0c0c0;vertical-align: middle; text-align: left;padding-top: 5px;" valign="top" width="21%"><div><a class="" href="https://thoughtworks-preview.jiveon.com/content?query=[Email]&amp;filterID=all~objecttype~objecttype[thread]" style="font-size: 12px;color:#1E90EB;text-decoration:none;">View all emails</a></div><div><a class="" href="https://thoughtworks-preview.jiveon.com/content?query=[Email]&amp;filterID=all~objecttype~objecttype[document]" style="font-size: 12px;color:#1E90EB;text-decoration:none;">View all attachments</a></div></td></tr></tbody></table></div></div></div><!-- [DocumentBodyEnd:33012154-d239-4a9e-b51a-d0f2d3ebfeb5] --></body>',
                                'editable': False}, 'typeCode': 2, 'index': '0', 'id': '1321016',
 'postedBy': '<a href="https://thoughtworks-preview.jiveon.com/people/$integration.tile.3030d7b4-c294-440b-b2b2-0db5f5f831bc" data-userid="7719" class="jiveTT-hover-user jive-username-link">StreamOnce Integration</a>',
 'unhelpfulCount': 0, 'visibleToExternalContributors': False,
 'discussion': 'https://thoughtworks-preview.jiveon.com/api/core/v3/contents/756454',
 'parentPlace': {'html': 'https://thoughtworks-preview.jiveon.com/groups/streamonce-automation', 'id': '58005',
                 'placeID': '756275', 'name': 'Streamonce-sissy-test',
                 'uri': 'https://thoughtworks-preview.jiveon.com/api/core/v3/places/756275', 'type': 'group',
                 'iconCss': 'jive-icon-group'}, 'outcomeTypes': [
    {'shareable': True, 'id': '3', 'name': 'pending', 'confirmUnmark': False, 'generalNote': False, 'urlAllowed': False,
     'type': 'outcomeType', 'noteRequired': True, 'confirmExclusion': False},
    {'shareable': False, 'id': '6', 'name': 'success', 'confirmUnmark': False, 'communityAudience': 'true',
     'generalNote': True, 'urlAllowed': False, 'type': 'outcomeType', 'noteRequired': False, 'confirmExclusion': False},
    {'shareable': False, 'id': '1', 'name': 'decision', 'confirmUnmark': False, 'generalNote': True,
     'urlAllowed': False, 'type': 'outcomeType', 'noteRequired': True, 'confirmExclusion': False},
    {'shareable': False, 'id': '4', 'name': 'helpful', 'confirmUnmark': False, 'alternativeGrouping': 'true',
     'generalNote': False, 'urlAllowed': False, 'type': 'outcomeType', 'noteRequired': False,
     'confirmExclusion': False}], 'abuseCount': 0, 'onBehalfOf': {'person': {'type': 'person', 'id': '60755',
                                                                             'resources': {'html': {
                                                                                 'ref': 'https://thoughtworks-preview.jiveon.com/people/cnctester1',
                                                                                 'allowed': ['GET']}, 'followers': {
                                                                                 'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@followers',
                                                                                 'allowed': ['GET']}, 'avatar': {
                                                                                 'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/avatar?a=4490',
                                                                                 'allowed': ['DELETE', 'PUT', 'GET']},
                                                                                           'members': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/members/people/60755',
                                                                                               'allowed': ['GET']},
                                                                                           'activity': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/activities',
                                                                                               'allowed': ['GET']},
                                                                                           'images': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/images',
                                                                                               'allowed': ['POST',
                                                                                                           'GET']},
                                                                                           'extprops': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/extprops',
                                                                                               'allowed': ['POST',
                                                                                                           'DELETE',
                                                                                                           'GET']},
                                                                                           'recognition': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@recognition',
                                                                                               'allowed': ['GET']},
                                                                                           'roles': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/roles',
                                                                                               'allowed': ['GET']},
                                                                                           'trendingPlaces': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@trendingPlaces',
                                                                                               'allowed': ['GET']},
                                                                                           'streams': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/streams',
                                                                                               'allowed': ['POST',
                                                                                                           'GET']},
                                                                                           'social': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@social',
                                                                                               'allowed': ['GET']},
                                                                                           'followingIn': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/followingIn',
                                                                                               'allowed': ['POST',
                                                                                                           'GET']},
                                                                                           'following': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@following',
                                                                                               'allowed': ['GET']},
                                                                                           'pages': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/pages',
                                                                                               'allowed': ['POST',
                                                                                                           'GET']},
                                                                                           'trendingContent': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@trendingContent',
                                                                                               'allowed': ['GET']},
                                                                                           'self': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755',
                                                                                               'allowed': ['DELETE',
                                                                                                           'PUT',
                                                                                                           'GET']},
                                                                                           'securityGroups': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/securityGroups',
                                                                                               'allowed': ['GET']},
                                                                                           'profilePrivacy': {
                                                                                               'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/profilePrivacy',
                                                                                               'allowed': ['GET']}},
                                                                             'displayName': 'CNC1 Tester1',
                                                                             'name': {'familyName': 'Tester1',
                                                                                      'givenName': 'CNC1',
                                                                                      'formatted': 'CNC1 Tester1'},
                                                                             'emails': [{'type': 'work',
                                                                                         'jive_showSummaryLabel': True,
                                                                                         'jive_summaryDisplayOrder': 2,
                                                                                         'jive_label': 'Email',
                                                                                         'value': 'cnctester1@dev.thoughtworks.com',
                                                                                         'primary': True,
                                                                                         'jive_displayOrder': 4}],
                                                                             'typeCode': 3, 'jive': {
        'level': {'name': 'Level 0', 'imageURI': '', 'description': 'Level 0', 'points': 0},
        'externalContributor': False, 'enabled': True, 'visible': True, 'username': 'cnctester1'}}},
 'via': {'displayName': 'StreamOnce'}, 'updated': '2017-05-03T04:08:37.845+0000', 'status': 'published',
 'helpfulCount': 0, 'published': '2017-05-03T04:08:37.845+0000', 'highlightTags': '', 'attachments': [],
 'author': {'type': 'person', 'mentionName': 'CNC1 Tester1', 'updated': '2017-04-27T07:40:53.206+0000',
            'displayName': 'CNC1 Tester1', 'followed': False, 'followingCount': 0,
            'published': '2017-02-07T12:09:20.969+0000', 'initialLogin': '2017-02-07T12:09:20.952+0000', 'id': '60755',
            'resources': {
                'html': {'ref': 'https://thoughtworks-preview.jiveon.com/people/cnctester1', 'allowed': ['GET']},
                'followers': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@followers',
                              'allowed': ['GET']},
                'avatar': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/avatar?a=4490',
                           'allowed': ['DELETE', 'PUT', 'GET']},
                'members': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/members/people/60755',
                            'allowed': ['GET']},
                'activity': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/activities',
                             'allowed': ['GET']},
                'images': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/images',
                           'allowed': ['POST', 'GET']},
                'extprops': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/extprops',
                             'allowed': ['POST', 'DELETE', 'GET']},
                'recognition': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@recognition',
                                'allowed': ['GET']},
                'roles': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/roles',
                          'allowed': ['GET']}, 'trendingPlaces': {
                    'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@trendingPlaces',
                    'allowed': ['GET']},
                'streams': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/streams',
                            'allowed': ['POST', 'GET']},
                'social': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@social',
                           'allowed': ['GET']},
                'followingIn': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/followingIn',
                                'allowed': ['POST', 'GET']},
                'following': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@following',
                              'allowed': ['GET']},
                'pages': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/pages',
                          'allowed': ['POST', 'GET']}, 'trendingContent': {
                    'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/@trendingContent',
                    'allowed': ['GET']},
                'self': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755',
                         'allowed': ['DELETE', 'PUT', 'GET']}, 'securityGroups': {
                    'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/securityGroups',
                    'allowed': ['GET']}, 'profilePrivacy': {
                    'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/profilePrivacy',
                    'allowed': ['GET']}}, 'phoneNumbers': [
         {'type': 'mobile', 'jive_displayOrder': 7, 'value': '+(86)13811814680', 'jive_showSummaryLabel': False,
          'jive_label': 'Mobile Phone Number'}],
            'thumbnailUrl': 'https://thoughtworks-preview.jiveon.com/api/core/v3/people/60755/avatar?a=4490',
            'name': {'familyName': 'Tester1', 'givenName': 'CNC1', 'formatted': 'CNC1 Tester1'}, 'followerCount': 0,
            'thumbnailId': '4490', 'emails': [
         {'type': 'work', 'jive_showSummaryLabel': True, 'jive_summaryDisplayOrder': 2, 'jive_label': 'Email',
          'value': 'cnctester1@dev.thoughtworks.com', 'primary': True, 'jive_displayOrder': 4}], 'typeCode': 3,
            'jive': {'visible': True, 'sendable': True, 'lastAuthenticated': '2017-04-27T07:40:53.205+0000',
                     'external': False, 'status': 'registered', 'locale': 'en', 'username': 'cnctester1',
                     'enabled': True, 'lastProfileUpdate': '2017-02-20T07:42:16.352+0000', 'federated': True,
                     'timeZone': 'America/Belize',
                     'level': {'name': 'Level 0', 'imageURI': '', 'description': 'Level 0', 'points': 0},
                     'externalContributor': False, 'profile': [
                    {'jive_displayOrder': 0, 'value': 'Dev', 'jive_showSummaryLabel': False, 'jive_label': 'Title'},
                    {'jive_displayOrder': 1, 'value': 'Connect', 'jive_showSummaryLabel': False,
                     'jive_label': 'Department'},
                    {'jive_displayOrder': 2, 'value': 'Wuhan', 'jive_showSummaryLabel': False,
                     'jive_label': 'working_office'},
                    {'jive_displayOrder': 5, 'value': 'Dev', 'jive_showSummaryLabel': False,
                     'jive_label': 'primary_role'},
                    {'jive_displayOrder': 6, 'value': 'Wuhan', 'jive_showSummaryLabel': False,
                     'jive_label': 'home_office'},
                    {'jive_displayOrder': 12, 'value': '1', 'jive_showSummaryLabel': False,
                     'jive_label': 'tw_experience'},
                    {'jive_displayOrder': 14, 'value': 'Con', 'jive_showSummaryLabel': False, 'jive_label': 'grade'}],
                     'externalIdentities': [{'identity': 'cnctester1', 'identityType': 'SAML'}]}},
 'resources': {'html': {'ref': 'https://thoughtworks-preview.jiveon.com/message/1321016', 'allowed': ['GET']},
               'attachments': {
                   'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/attachments/messages/1321016',
                   'allowed': ['POST', 'GET']},
               'helpful': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/helpful',
                           'allowed': ['POST', 'GET']},
               'outcomes': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/outcomes',
                            'allowed': ['POST', 'GET']},
               'likes': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/likes',
                         'allowed': ['POST', 'GET']},
               'editHTML': {'ref': 'https://thoughtworks-preview.jiveon.com/message/1321016/edit', 'allowed': ['GET']},
               'extprops': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/extprops',
                            'allowed': ['POST', 'DELETE', 'GET']},
               'self': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016',
                        'allowed': ['DELETE', 'PUT', 'GET']},
               'messages': {'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/messages',
                            'allowed': ['POST', 'GET']}, 'outcomeTypes': {
         'ref': 'https://thoughtworks-preview.jiveon.com/api/core/v3/messages/1321016/outcomeTypes',
         'allowed': ['GET']}}, 'uuid': 'a7a08704-819e-48ac-8796-71c03ac948db', 'followerCount': 0,
 'subject': 'Discussion and reply with attachment by Email2017-05-03T12:07:44.582516',
 'iconCss': 'jive-icon-discussion',
 'highlightBody': ', which then develops into another polyp.  &#160; &#160; &#160; &#160; Comments/<em class="jive-hilite">replies</em> will be emailed to: cnctester1@dev.thoughtworks.com; streamonce-automation@dev.thoughtworks.com;  View all emails  View all ',
 'messageTarget': 'replyAsComment'}
