version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
      - image: selenium/standalone-chrome:latest
    steps:
      - run:
         name: Install Requirements & run test
         command: |
             pip install virtualenv
             virtualenv venv
             source venv/bin/activate
             pip install -r requirements.txt
             bash testRunner.sh

