version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Create json
          command: |
             cat <<EOF> ./streamonce-testing-c911366674f7.json
             {"type": "service_account", "project_id": "streamonce-testing","private_key_id": "c911366674f730b47a1c2774155175cc03a1e49e","private_key": "${PRIVATE_KEY}","client_email": "streamonce-testing@appspot.gserviceaccount.com","client_id": "107495441022329297030","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamonce-testing%40appspot.gserviceaccount.com"}
             EOF
             ls
      - run:
         name: Install Requirements & run test
         command: |
             pip install virtualenv
             virtualenv venv
             source venv/bin/activate
             pip install -r requirements.txt
             bash testRunner.sh

